채팅방 내 Plain Text 메시지 발송 시, 저장 로직을 추가합니다.
pet-sitter/pets-next-door-api pull request #100
Opened 2024-12-15 14:39 UTC by JoeCP17

## 추가내용 
1. 채팅 메시지 발송 시, 메시지를 저장하는 로직을 추가합니다. 
2. go version 을 1.23 -> 1.23.0으로 버전 수정을 진행합니다. 

### go version 변경내용 
make build 또는 프로젝트를 열었을 시, 아래와 같은 이슈가 발생했습니다. 
`Go toolchain not available`

해당 이슈의 경우 major, minor 버전 명시가 안되어 있을 경우 발생하는 이슈임으로 파악했고 참고했던 링크는 아래와 같습니다. 
[stack overflow 바로가기](https://stackoverflow.com/questions/78519711/toolchain-not-available-error-prevents-me-from-using-any-go-commands)

### 채팅방 메시지 저장 
메시지 저장 시, 현재 plain 텍스트는 row가 아래와 같이 저장됨을 확인했습니다. 
![image](https://github.com/user-attachments/assets/aa9a7065-6e22-44e4-9595-be6993f9405f)

현재 plain Text 발송 시 저장되고 있는데 미디어쪽도 추가로직 구현을 진행하려 합니다.

2024-12-23 10:49 UTC, litsynp requested changes

2024-12-23 10:49 UTC, litsynp commented on internal/service/chat_service.go
> +) (*chat.Message, *pnd.AppError) {
이거 리베이스하면 아마 오류날 거에요. 이렇게 바꿔주시면 작동할 것 같습니다.

```suggestion
) (*chat.Message, error) {
```

2024-12-23 10:49 UTC, litsynp commented on internal/service/chat_service.go
> +		return nil, pnd.FromPostgresError(transactionError.Err)
여기도 마찬가지

```suggestion
		return nil, pnd.FromPostgresError(transactionError)
```

2024-12-23 10:49 UTC, litsynp commented on internal/service/chat_service.go
> +		return nil, pnd.FromPostgresError(databaseGenError)
여긴 이렇게 바꿔주시면 될 것 같습니다
```suggestion
		return nil, databaseGenError
```

2024-12-23 10:49 UTC, litsynp commented on internal/service/chat_service.go
> +	tx.Commit()
여긴 lint에서 아마 걸릴 것 같아요. 이렇게 바꾸면 될 듯 합니다
```suggestion
	if err := tx.Commit(); err != nil {
		return nil, err
	}
```

2024-12-23 10:50 UTC, litsynp commented
리베이스하고 빌드 돌리면 아마 fail 날텐데 코멘트 한번 읽어주세요!

2025-01-19 13:13 UTC, JoeCP17 commented
go lint 라인 수 조정을 진행합니다. 160 -> 180

2025-02-01 13:51 UTC, litsynp approved these changes

2025-02-02 11:16 UTC, JoeCP17 commented on .golangci.yml
> +    - copyloopvar # checks for pointers to enclosing loop variables
exportloopref는 Go 1.22에서 loopvar로 대체되었기에, 버전 호환을 위해 변경을 진행합니다.

2025-02-18 13:42 UTC, litsynp approved these changes

2025-02-18 16:12 UTC, merged