돌봄급구 수정 API 에러를 해결합니다.
pet-sitter/pets-next-door-api pull request #26
Opened 2023-12-18 16:32 UTC by barabobBOB

## 작업내용

- 돌봄급구 수정 API에서 상황에 맞지 않은 403 에러가 반환되는 이슈를 수정하였습니다.
- 게시글 조회 Response 타입에 created_at, updated_at 를 추가하였습니다.
- Swagger 돌봄급구 API에서 불필요한 Security를 제거하였습니다.

## 테스트

/posts/sos [PUT]

Request (예시)
{
  "care_type": "foster",
  "carer_gender": "male",
  "condition_ids": [
    1, 2, 3
  ],
  "content": "content",
  "date_end_at": "2020-10-06T10:00:00+09:00",
  "date_start_at": "2020-10-16T18:00:00+09:00",
	"id": 1,
  "image_ids": [
    1
  ],
  "pet_ids": [
    1
  ],
  "reward": "string",
  "reward_amount": "hour",
  "time_end_at": "10:00",
  "time_start_at": "18:00",
  "title": "title"
}

2023-12-19 10:28 UTC, litsynp requested changes

2023-12-19 10:28 UTC, litsynp commented on cmd/server/handler/sos_post_handler.go
> +
여긴 Security를 뺐는데 왜 추가된건가요?

2023-12-19 10:28 UTC, litsynp commented on internal/domain/sos_post/service.go
> +func (service *SosPostService) WriteSosPost(uid int, request *WriteSosPostRequest) (*WriteSosPostResponse, error) {
음...? 파이어베이스 uid를 말하는 거라면 string 타입입니다.
Atoi 해서 받아오고 있는 것 같은데 handler 단부터 잘못된 것 같아요. 인증 헤더의 토큰을 읽어야 합니다.

https://github.com/pet-sitter/pets-next-door-api/blob/7038589/db/migrations/000001_create_users_table.up.sql#L8

2023-12-19 10:28 UTC, litsynp commented on internal/domain/sos_post/service.go
> +func (service *SosPostService) CheckUpdatePermission(uid int, sosPostID int) bool {
여기도 마찬가지입니당.

2023-12-19 10:28 UTC, litsynp commented on internal/domain/sos_post/service.go
> +	userID, _ := service.userStore.FindUserIDByUID(uid)
왜 uid가 int로 들어갔는데 컴파일 에러가 안났나 했더니 FindUserIDByUID 함수부터 잘못됐군요.

https://github.com/pet-sitter/pets-next-door-api/blob/a90b3ae/internal/postgres/user_store.go#L149C29-L171

2023-12-19 17:04 UTC, barabobBOB commented on internal/domain/sos_post/service.go
> +	userID, _ := service.userStore.FindUserIDByUID(uid)
int 데이터를 넣어도 쿼리를 작성하면서 자동으로 string으로 타입변환 되면서 동작에는 문제가 없었던 것 같아요.
연관된 함수 모두 수정하겠습니다.

2023-12-21 14:33 UTC, litsynp commented on internal/postgres/user_store.go
> +func (s *UserPostgresStore) FindUserIDByUID(uid string) (int, error) {
uid 라는 변수명이 장기적으로 봤을 때 혼동의 여지가 있을 것 같아요. 여기서 uid는 DB상으로도 `fb_uid`, 앱에서도 firebase의 uid만 들어갈 수 있으니, 코드에서 `fbUid`로 통일하는 게 어떨까요? 이 함수의 경우에는 `FindUserIDByFbUID`가 되겠네요.

2023-12-21 14:33 UTC, litsynp commented on internal/domain/user/user.go
> +	FindUserIDByUID(uid string) (int, error)
아래에 남긴 comment에 따라 interface에서도 자연스럽게 함수명 및 변수명을 바꾸면 좋을 것 같아요.

2023-12-21 14:33 UTC, litsynp commented on internal/domain/sos_post/service.go
> +func (service *SosPostService) CheckUpdatePermission(uid string, sosPostID int) bool {
아래 참고, 여기도요

2023-12-21 14:33 UTC, litsynp commented on internal/domain/sos_post/service.go
> +func (service *SosPostService) WriteSosPost(uid string, request *WriteSosPostRequest) (*WriteSosPostResponse, error) {
아래 참고, 여기도요

2023-12-21 14:33 UTC, litsynp commented on cmd/server/handler/sos_post_handler.go
> +	uid := foundUser.FirebaseUID
이건 굳이 변수 할당이 필요 없을 것 같습니다.

2023-12-21 14:33 UTC, litsynp commented on cmd/server/handler/sos_post_handler.go
> +	uid := foundUser.FirebaseUID
이건 굳이 변수 할당이 필요 없을 것 같습니다.

2023-12-21 14:55 UTC, barabobBOB commented on internal/postgres/user_store.go
> +func (s *UserPostgresStore) FindUserIDByUID(uid string) (int, error) {
좋은 것 같습니다. 수정해두도록 할게요 :)

2023-12-21 22:33 UTC, litsynp approved these changes
👍

2023-12-22 12:52 UTC, merged