채팅 기능을 추가합니다.
pet-sitter/pets-next-door-api pull request #80
Opened 2024-06-03 16:02 UTC by barabobBOB

✅ 채팅 진행 사항
---
- 채팅방을 통한 일대일, 일대다 채팅 기능을 추가하였습니다.
- 웹소켓 ([gorilla/websocket](https://github.com/gorilla/websocket)) 활용하였습니다.
- map과 channel을 통해 채팅 브로드캐스트합니다.
- 서버가 재시작 되어도 채팅방 상태를 복구하기 위한 `internal/chat/init.go` 추가하였습니다.

Test
---
1. Postman -> websocket
2. 헤더에 Key = `Authorization`, Value = 'Bearer XXXX' 추가
3. 채팅방 조인
  ```
{
    "action": "JOIN_ROOM",
    "message": "",
    "target": {
        "id": 1,
        "name": "채팅방",
        "roomType": "personal"
    },
    "messageType": ""
}
```
만일, 해당하는 `id`의 채팅이 존재하지 않는다면 새로운 i`d`의 채팅방 생성됩니다. (응답값의 `id`에서 확인 가능)

4. 메시지 전송
  ```
{
    "action": "SEND_MESSAGE",
    "message": "안녕?",
    "target": {
        "id": 1,
        "name": "",
        "roomType": "personal"
    },
    "messageType": "normal"
}
```

이후에 클라이언트의 요청에 맞춰서 요청, 응답값을 수정할 예정입니다. 현재 에러 핸들링 등 여러모로 코드가 복잡한데, 차차 수정해나갈 예정입니다.

2024-06-22 04:54 UTC, litsynp commented
Test

2024-06-30 08:16 UTC, JoeCP17 commented
어제 리뷰당시 이야기나눴던 내용 다시 남겨봅니다. 
1. 각 메서드별 맥락 추측이 가능한 코드로 리펙토링 진행했으면 좋겠습니다.
2. 예제의 코드를 그대로 사용하는것이 아니라, 이웃집 멍냥이 요구사항의도에 맞는 코드로 활용해서 작성해주셨으면 좋겠습니다. 
3. Wait Time의 경우 임의로 시간을 늘리는 것이 아닌, 현재 발생하는 Latency을 기준으로 선정하여 작성해주셨으면 좋겠습니다. 
4. 테스트 방법과 어떻게 테스트를 진행했는지 공유가 가능했으면 좋겠습니다. 
5. 채팅 메시지의 Length가 넘어갈 경우와 같은 예외상황에 대한 처리도 있으면 좋겠습니다.

2024-07-15 00:49 UTC, barabobBOB commented on cmd/server/handler/chat_handler.go
> +	WriteBufferSize: 2048,
카카오톡에서 최대 글자수를 1000자로 제한하고 있습니다. 이웃집멍냥은 사담 위주의 서비스이기에 약 한국어 기준으로 카카오톡의 절반 정도 되는 바이트 수로 결정했습니다. 필요에 따라 늘려도 좋을 것 같습니다.

2024-07-15 00:51 UTC, barabobBOB commented on cmd/server/router.go
> +	stateManager := chat.NewInMemoryStateManager()
현재는 인메모리 기반으로 구현되어있습니다. 추후 Redis로 변경할 것을 대비하여 RedisManager처럼 구현체를 만들어 대체하기 쉽도록 하였습니다.

2024-07-15 00:56 UTC, barabobBOB commented on internal/chat/client.go
> +	pingPeriod     = (pongWait * 9) / 10
writeWait는 보통 5 ~ 15초 사이를 사용한다고 합니다. 
pongWait는 일반적으로 30 ~ 120초 사이를 사용합니다. 
pingPeriod는 70 ~ 90%를 사용합니다.
모두 사이값을 기준으로 설정하게 되었습니다.

2024-07-16 16:52 UTC, JoeCP17 requested changes
확인했어요 코멘트 확인부탁드려요~

2024-07-16 16:52 UTC, JoeCP17 commented on cmd/server/handler/user_handler.go
> +	// }
해당 항목은 사용되지 않는건가요? 만약 그렇다면 삭제해주시면 좋을것 같습니다.

2024-07-16 16:52 UTC, JoeCP17 commented on internal/chat/client.go
> +		return pnd.NewAppError(nil, http.StatusBadRequest, pnd.ErrCodeInvalidBody, "채팅방 정보가 nil입니다.")
각 에러 메시지에 트래킹 할 수 있게, 식별자 넣어주세요. 

해당 이슈가 발생했을때 로그로 트래킹이 어려울 것 같습니다. 
아니면 최소한 시스템 로그로라도 남길수있게 해주세요.` ( ex> java -> log.error("Join chat room must not be empty userId = {} , chat room = {} , user.userId, roomId ); )  `

2024-07-16 18:43 UTC, barabobBOB commented on internal/chat/client.go
> +		return pnd.NewAppError(nil, http.StatusBadRequest, pnd.ErrCodeInvalidBody, "채팅방 정보가 nil입니다.")
식별자 포함한 에러메시지로 변경하도록 하겠습니다 👍🏻

2024-07-16 18:45 UTC, barabobBOB commented on cmd/server/handler/user_handler.go
> +	// }
이 부분 실수로 주석처리 한 것 같습니다. 롤백 해두도록 할게요 !

2024-07-16 19:09 UTC, barabobBOB commented on internal/chat/client.go
> +		return pnd.NewAppError(nil, http.StatusBadRequest, pnd.ErrCodeInvalidBody, "채팅방 정보가 nil입니다.")
```
func (client *Client) setupConnection() *pnd.AppError {
	err := client.Conn.SetReadDeadline(time.Now().Add(pongWait))
	if err != nil {
		return pnd.NewAppError(err, http.StatusInternalServerError, pnd.ErrCodeUnknown, "읽기 제한 시간 설정에 실패했습니다. [setupConnection:1]")
	}

	client.Conn.SetPongHandler(func(string) error {
		err := client.Conn.SetReadDeadline(time.Now().Add(pongWait))
		if err != nil {
			return pnd.NewAppError(err, http.StatusInternalServerError, pnd.ErrCodeUnknown, "Pong 핸들러 설정에 실패했습니다. [setupConnection:2]")
		}
		return nil
	})
	return nil
}
```

이런 식으로 :1, :2로 식별자를 붙히는 형태는 어떤가요?

2024-07-17 13:00 UTC, litsynp reviewed
코멘트 달고 버튼을 안눌렀네요

리뷰 준비되면 draft에서 ready for review 상태로 넘겨주세요~

2024-07-18 09:14 UTC, barabobBOB commented on internal/chat/in_memory_state_manager.go
> +	rooms   map[int64]*Room
굳이 DB에서 조회하지 않고 빠르게 Room에 대한 정보를 가져올 수 있다고 생각했었습니다.
다시 생각해보니 입장, 퇴장, 채팅방 정보 자체를 이미 DB에서 관리중이기 때문에 불필요한 부분이 맞다고 생각이 드네요.
DB에서 가져오도록 수정하겠습니다 !

2024-07-18 09:19 UTC, barabobBOB commented on internal/chat/in_memory_state_manager.go
> +	roomClients map[int64]map[string]*Client
오.. 좋은 방법인데요? 
`roomClients map[int64][]string` 으로 변경하고 string은 UID를 가지면 좋겠네요. 수정하겠습니다.

2024-07-18 09:24 UTC, barabobBOB commented on internal/chat/in_memory_state_manager.go
> +	clientRooms map[string]map[int64]struct{}
추후 Redis를 도입한다면, client에서는 따로 채팅방 ID 목록이 필요하지 않고 클라이언트와 방 정보를 Redis에 저장하고 조회하는 방식이기 때문에 그대로 가져가는 것이 더 맞다고 생각합니다.

2024-07-18 09:27 UTC, litsynp commented on internal/chat/in_memory_state_manager.go
> +	clientRooms map[string]map[int64]struct{}
in memory 구현체라서 redis는 여기서 신경 안써도 될 것 같긴 합니다! 어차피 struct는 interface에 안들어가서요.

2024-07-18 09:29 UTC, litsynp commented on internal/chat/client.go
> +		return pnd.NewAppError(nil, http.StatusBadRequest, pnd.ErrCodeInvalidBody, "채팅방 정보가 nil입니다.")
제 생각에는 :1, 2: 같은 건 없애도 것 같아요. 어차피 읽기 제한 ~, Pong 핸들러 ~로 필터해서 볼수 있으니까요. 채팅방 ID등 식별자 넣는 건 좋은 것 같습니다. :+1:

2024-07-18 10:11 UTC, barabobBOB commented on internal/chat/in_memory_state_manager.go
> +	clientRooms map[string]map[int64]struct{}
in-memory 구현체에서 추가되는게 아니라 `chat/client`의 struct에서 추가되어야 하는데, 추가한다고 하면 나중에 Redis로 바꿀때 삭제될 부분인 것 같습니다! 어떻게 생각하시나요?

2024-07-18 10:36 UTC, litsynp commented on internal/chat/in_memory_state_manager.go
> +	clientRooms map[string]map[int64]struct{}
이 부분은 그럼 Redis 도입할 때 어차피 안쓰게 될테니 넘어가도 될 것 같아요.
근데 그러고보니 `StateManager`는 `handler`, `client` 중에 하나(`handler`)에만 있으면 되지 않나요?

2024-07-18 10:53 UTC, barabobBOB commented on internal/chat/in_memory_state_manager.go
> +	clientRooms map[string]map[int64]struct{}
그러네요. client를 `handler`에서 실행시키게 되니 필요없네요. 없애도록 하겠습니다 !

2024-07-18 14:54 UTC, barabobBOB commented on internal/chat/in_memory_state_manager.go
> +	rooms   map[int64]*Room
변경중, 고려하지 못한 사항이 있었습니다.

현재 `Room`에는 채팅방 정보 외에 채널 통해서 이벤트를 처리하고 있습니다.

```
type Room struct {
         ...

	RegisterChan   chan *Client  `json:"-"`
	UnregisterChan chan *Client  `json:"-"`
	BroadcastChan  chan *Message `json:"-"`
}
```

채팅방 정보는 제거하더라도 채팅방 별로 이벤트 처리를 위한 채널을 가진 객체를 가지고 있어야만 합니다.
그래서 제 생각에는 두가지 방법이 있을 것 같습니다.
1. 채팅방 정보 struct와 채팅방 별로 이벤트 처리를 위한 채널을 가진 struct을 나누고 채팅방 정보를 DB에서만 관리하는 방식.
2. 현상태 그대로.

2024-07-18 15:30 UTC, litsynp commented on internal/chat/in_memory_state_manager.go
> +	rooms   map[int64]*Room
일단 이건 그대로 두죠. 어차피 채팅방 생성 기능 분리하면서 DB의 Room이랑 웹소켓의 그것이랑 매핑 작업이 추가로 필요할 거 같아요 (이건 제가 PR 머지 후 고민해볼게요..)

2024-07-20 10:49 UTC, JoeCP17 approved these changes
고생하셨습니다.

컴플릭트 생긴 부분들 확인해주세요~

2024-07-20 14:11 UTC, merged